import { StyleSheet } from 'react-native';
import { colors, radius, shadows, spacing, typography } from '@/theme';

export const receiptStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing['2xl'],
    paddingTop: spacing['2xl'],
    paddingBottom: spacing.md,
    backgroundColor: colors.surface,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.border,
  },
  topBarBalance: {
    width: 22,
  },
  topBarTitle: {
    ...typography.lg,
    fontWeight: '600' as const,
    color: colors.textPrimary,
  },
  scrollContent: {
    paddingHorizontal: spacing['2xl'],
    paddingTop: spacing.xl,
    paddingBottom: 32,
  },
  successHeader: {
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  successCircle: {
    width: 56,
    height: 56,
    borderRadius: radius.full,
    backgroundColor: colors.success,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
    ...shadows.hover,
  },
  successTitle: {
    ...typography['2xl'],
    fontWeight: '700' as const,
    color: colors.textPrimary,
    marginBottom: spacing.xs,
  },
  successSubtitle: {
    ...typography.md,
    color: colors.textSecondary,
  },
  receiptCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    ...shadows.modal,
    marginBottom: spacing.lg,
    overflow: 'hidden',
  },
  receiptHeader: {
    alignItems: 'center',
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.xl,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.border,
  },
  receiptIconCircle: {
    width: 44,
    height: 44,
    borderRadius: radius.full,
    backgroundColor: colors.iconCircle,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.sm,
  },
  receiptBrand: {
    ...typography.lg,
    fontWeight: '700' as const,
    color: colors.textPrimary,
    marginBottom: spacing.xs,
  },
  receiptAddress: {
    ...typography.xs,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 16,
  },
  receiptMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.border,
  },
  receiptMetaText: {
    ...typography.sm,
    color: colors.textSecondary,
  },
  receiptItems: {
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.border,
    gap: spacing.sm,
  },
  itemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  itemName: {
    flex: 1,
    ...typography.sm,
    color: colors.textSecondary,
  },
  itemSubtotal: {
    ...typography.sm,
    color: colors.textPrimary,
  },
  receiptTotals: {
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.border,
    gap: spacing.sm,
  },
  receiptGrandTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.border,
  },
  grandTotalLabel: {
    ...typography.md,
    fontWeight: '700' as const,
    color: colors.textPrimary,
  },
  grandTotalValue: {
    ...typography.xl,
    fontWeight: '700' as const,
    color: colors.textPrimary,
  },
  paymentMethodRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.sm,
  },
  paymentMethodLabel: {
    ...typography.xs,
    color: colors.textSecondary,
    letterSpacing: 0.6,
  },
  paymentMethodValue: {
    ...typography.sm,
    fontWeight: '600' as const,
    color: colors.textPrimary,
  },
  dashedDivider: {
    borderTopWidth: 1,
    borderTopColor: colors.border,
    borderStyle: 'dashed',
    marginHorizontal: spacing.lg,
    marginVertical: spacing.md,
  },
  barcodeSection: {
    alignItems: 'center',
    paddingHorizontal: spacing.xl,
    paddingBottom: spacing.lg,
  },
  barcodePlaceholder: {
    width: '100%',
    height: 64,
    backgroundColor: colors.textPrimary,
    borderRadius: radius.sm,
    marginBottom: spacing.sm,
  },
  barcodeText: {
    ...typography.xs,
    color: colors.textSecondary,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  receiptEdge: {
    height: 16,
    backgroundColor: colors.background,
  },
  actions: {
    gap: spacing.sm,
    marginBottom: spacing.lg,
  },
  newTransactionButton: {
    backgroundColor: colors.primary,
    borderRadius: radius.full,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    ...shadows.active,
  },
  newTransactionButtonText: {
    ...typography.lg,
    fontWeight: '600' as const,
    color: colors.surface,
  },
  secondaryRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  secondaryButton: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: radius.full,
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.resting,
  },
  secondaryButtonPressed: {
    backgroundColor: colors.navActive,
  },
  secondaryButtonText: {
    ...typography.md,
    fontWeight: '500' as const,
    color: colors.textPrimary,
  },
});
