-- 0001_init.sql
-- Schema for IPSS (Integrated POS and Stock Monitoring System for Cafe Elvira)
-- Tables match the columns referenced by the app's Supabase queries.
-- NOTE: policies are intentionally permissive for the local/dev preview
-- environment. Row-level security is tightened to role-based access as a
-- separate follow-up (see AGENTS.md > Data Privacy).

-------------------------------------------------
-- Product catalog
-------------------------------------------------
create table if not exists product (
  product_id   bigint   generated by default as identity primary key,
  name         text     not null,
  category     text     not null,
  price        numeric  not null default 0,
  is_available boolean  not null default true
);

-------------------------------------------------
-- App users (profile rows) + link to Supabase Auth
-------------------------------------------------
create table if not exists "user" (
  user_id     uuid    primary key references auth.users not null,
  username    text    unique not null,
  password    text,          -- legacy/seed column; auth itself lives in auth.users
  role        text    not null default 'cashier' check (role in ('admin', 'cashier')),
  is_active   boolean not null default true
);

-------------------------------------------------
-- Inventory
-------------------------------------------------
create table if not exists inventory (
  stock_id       bigint generated by default as identity primary key,
  product_id     bigint not null references product (product_id) on delete cascade,
  quantity       integer not null default 0,
  reorder_level  integer not null default 0
);

-------------------------------------------------
-- Transactions (online)
-------------------------------------------------
create table if not exists transactions (
  id            uuid          primary key,
  total_amount  numeric       not null default 0,
  payment_mode  text          not null,
  user_id       uuid          not null references "user" (user_id),
  date          timestamptz   not null,
  status        text          not null default 'completed',
  void_reason   text,
  amount_received numeric,
  change_given    numeric
);

-- Index used by the cashier "own transactions" filter
create index if not exists idx_transactions_user on transactions (user_id);

-------------------------------------------------
-- Transaction line items
-------------------------------------------------
create table if not exists transaction_items (
  id             uuid  primary key,
  transaction_id uuid  not null references transactions (id) on delete cascade,
  product_id     bigint not null references product (product_id),
  quantity       integer not null,
  subtotal       numeric not null
);

-------------------------------------------------
-- Stock movements (audit trail)
-------------------------------------------------
create table if not exists stock_movements (
  movement_id bigint generated by default as identity primary key,
  stock_id    bigint not null references inventory (stock_id) on delete cascade,
  type        text   not null check (type in ('in', 'out')),
  quantity    integer not null,
  date        timestamptz not null,
  supplier    text
);

-------------------------------------------------
-- Row-level security (permissive for dev preview)
-------------------------------------------------
alter table product           enable row level security;
alter table "user"            enable row level security;
alter table inventory         enable row level security;
alter table transactions      enable row level security;
alter table transaction_items enable row level security;
alter table stock_movements   enable row level security;

-- Authenticated role may manage everything.
create policy "authenticated full access" on product using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "authenticated full access" on "user" using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "authenticated full access" on inventory using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "authenticated full access" on transactions using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "authenticated full access" on transaction_items using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "authenticated full access" on stock_movements using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- Anon role may read the catalog while unauthenticated.
create policy "anon can read catalog" on product using (auth.role() = 'anon');
create policy "anon can read catalog" on "user" using (false);
create policy "anon can read catalog" on inventory using (auth.role() = 'anon');
