import { StyleSheet } from 'react-native';
import { colors, radius, shadows, spacing, typography } from '@/theme';

export const receiptViewStyles = StyleSheet.create({
  root: {},
  receiptCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    ...shadows.modal,
    marginBottom: spacing.lg,
    overflow: 'hidden',
  },
  receiptHeader: {
    alignItems: 'center',
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.xl,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.border,
  },
  receiptIconCircle: {
    width: 44,
    height: 44,
    borderRadius: radius.full,
    backgroundColor: colors.iconCircle,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.sm,
  },
  receiptBrand: {
    ...typography.lg,
    fontWeight: '700' as const,
    color: colors.textPrimary,
    marginBottom: spacing.xs,
  },
  receiptAddress: {
    ...typography.xs,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 16,
  },
  cashierRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.xl,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.border,
  },
  cashierLabel: {
    ...typography.xs,
    color: colors.textSecondary,
  },
  cashierValue: {
    ...typography.xs,
    fontWeight: '500' as const,
    color: colors.textPrimary,
  },
  voidBanner: {
    backgroundColor: colors.dangerSurface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.dangerBorder,
    padding: spacing.sm,
    marginVertical: spacing.sm,
    marginHorizontal: spacing.xl,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  voidBannerText: {
    ...typography.xs,
    fontWeight: '600' as const,
    color: colors.danger,
    letterSpacing: 0.5,
  },
  voidReason: {
    ...typography.xs,
    color: colors.textSecondary,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  receiptMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.border,
  },
  receiptMetaText: {
    ...typography.sm,
    color: colors.textSecondary,
  },
  receiptItems: {
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.border,
    gap: spacing.sm,
  },
  itemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  itemName: {
    flex: 1,
    ...typography.sm,
    color: colors.textSecondary,
  },
  itemSubtotal: {
    ...typography.sm,
    color: colors.textPrimary,
  },
  receiptTotals: {
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.border,
    gap: spacing.sm,
  },
  receiptGrandTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.border,
  },
  grandTotalLabel: {
    ...typography.md,
    fontWeight: '700' as const,
    color: colors.textPrimary,
  },
  grandTotalValue: {
    ...typography.xl,
    fontWeight: '700' as const,
    color: colors.textPrimary,
  },
  paymentMethodRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.sm,
  },
  paymentMethodLabel: {
    ...typography.xs,
    color: colors.textSecondary,
    letterSpacing: 0.6,
  },
  paymentMethodValue: {
    ...typography.sm,
    fontWeight: '600' as const,
    color: colors.textPrimary,
  },
  amountRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.xs,
  },
  amountLabel: {
    ...typography.xs,
    color: colors.textSecondary,
  },
  amountValue: {
    ...typography.xs,
    color: colors.textPrimary,
  },
  amountValueChange: {
    ...typography.xs,
    fontWeight: '600' as const,
    color: colors.primary,
  },
  dashedDivider: {
    borderTopWidth: 1,
    borderTopColor: colors.border,
    borderStyle: 'dashed',
    marginHorizontal: spacing.lg,
    marginVertical: spacing.md,
  },
  barcodeSection: {
    alignItems: 'center',
    paddingHorizontal: spacing.xl,
    paddingBottom: spacing.lg,
  },
  barcodeText: {
    ...typography.xs,
    color: colors.textSecondary,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  actions: {
    gap: spacing.sm,
    marginBottom: spacing.lg,
  },
  secondaryRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  secondaryButton: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: radius.full,
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.resting,
  },
  secondaryButtonPressed: {
    backgroundColor: colors.navActive,
  },
  secondaryButtonText: {
    ...typography.md,
    fontWeight: '500' as const,
    color: colors.textPrimary,
  },
});
